In [1]:
#Average Mahalanobis Distance 
import numpy as np
from scipy.spatial.distance import mahalanobis

In [2]:
def avg_mahalanobis_distance(predicted, ground_truth):
    #here
    predicted = np.array(predicted)
    ground_truth = np.array(ground_truth)
    mean_predicted = np.mean(predicted, axis=0)
    mean_ground_truth = np.mean(ground_truth, axis=0)
    cov_predicted = np.cov(predicted.T)
    cov_ground_truth = np.cov(ground_truth.T)
    inv_cov_predicted = np.linalg.inv(cov_predicted)
    inv_cov_ground_truth = np.linalg.inv(cov_ground_truth)
    error = 0
    for i in range(len(predicted)):
        error += mahalanobis(predicted[i], ground_truth[i], inv_cov_predicted + inv_cov_ground_truth)
    return error / len(predicted)


In [15]:
len(pred)

3

In [13]:
pred = [[90,64],[65,32], [96,68]]
gt = [[92,80], [60,30],[100,70]]

In [14]:
err = avg_mahalanobis_distance(pred, gt)
print(err)

4.27858489728556


In [7]:
predicted_coordinates = [[1.3, 2.4, 4.2], [3.12, 4.23, 3.1], [5.12, 6.6, 4.6], [7.5, 8.5, 6.7]]
ground_truth_coordinates = [[2.0, 3.2, 4.0], [4.0, 5.3, 4.3], [6.2, 7.33, 4.5], [8.7, 9.2, 7.0]]

# print(inv_cov_predicted)
error = avg_mahalanobis_distance(predicted_coordinates, ground_truth_coordinates)
print(error)


5.370587172684321


In [10]:
from numpy.linalg import inv
mat = [[448, 520],[520, 700]]
mat_in = inv(mat)
mat_in

array([[ 0.0162037 , -0.01203704],
       [-0.01203704,  0.01037037]])

In [16]:
import numpy as np
from numpy.linalg import inv

def average_mahalanobis_distance(data, mean, cov):
    # Calculate the inverse of the covariance matrix
    cov_inv = inv(cov)

    # Calculate the Mahalanobis distance for each data point
    distances = []
    for i in range(data.shape[0]):
        diff = data[i,:] - mean
        distance = np.dot(np.dot(diff, cov_inv), diff)
        distances.append(distance)

    # Calculate the average Mahalanobis distance
    avg_distance = np.mean(distances)

    return avg_distance


In [21]:
data1 = np.array([90, 64]) #2x1
data2 = np.array[[84], [60]] #1x2
average_mahalanobis_distance(data1, data2, mat_in)

TypeError: 'builtin_function_or_method' object is not subscriptable

A non-singular matrix is required to find the AMD. A matrix is singular iff its determinant is Zero. The prediction and ground truth trajectory data represented in matrix form must be able to be represented as square matrix with inverse possible. 

In [17]:
np.linalg.matrix_rank(predicted_coordinates)

2

In [18]:
p = np.array(predicted_coordinates)
p.shape

(4, 2)

In [19]:
p.T

array([[1.3 , 3.12, 5.12, 7.5 ],
       [2.4 , 4.23, 6.6 , 8.5 ]])

In [20]:
v = np.cov(p.T)
v

array([[7.09946667, 7.0966    ],
       [7.0966    , 7.138225  ]])

In [21]:
np.linalg.inv(v)

array([[ 22.59941164, -22.46762811],
       [-22.46762811,  22.47670389]])

In [29]:
u = np.array(ground_truth_coordinates)
u.shape

(4, 2)

In [30]:
u.T

array([[2.  , 4.  , 6.2 , 8.7 ],
       [3.2 , 5.3 , 7.33, 9.2 ]])

In [31]:
x = np.cov(u.T)
x

array([[8.30916667, 7.43475   ],
       [7.43475   , 6.691225  ]])